name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.15.0
      options: --user 1001
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: clean:reports
        run: npm run clean:reports

      - name: Run Cypress tests
        run: npm run test:chrome || true

      - name: Merge test results
        run: npm run report:merge

      - name: Generate Mochawesome HTML report
        run: npm run report:generate

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mocha-report
          path: cypress/mochawesome-html-report/index.html

      - name: Deploy to GitHub Pages
        if: success() || failure()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/mochawesome-html-report
